In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [13]:
annual_hospitalizations = pd.read_csv('../Data/Annual_Hospitalizations_for_Asthma.csv')
annual_hospitalizations.head()

   StateFIPS    State  Year Value  Data Comment  Unnamed: 5   Age Group"Sex
0          4  Arizona  2022   279           NaN         NaN     0 TO 4"Male
1          4  Arizona  2022   154           NaN         NaN   0 TO 4"Female
2          4  Arizona  2022   382           NaN         NaN    5 TO 14"Male
3          4  Arizona  2022   289           NaN         NaN  5 TO 14"Female
4          4  Arizona  2022   139           NaN         NaN   15 TO 34"Male

In [14]:
annual_hospitalizations.describe()

        StateFIPS    Year  Data Comment  Unnamed: 5
count  270.000000   270.0           0.0         0.0
mean    30.555556  2022.0           NaN         NaN
std     15.002685     0.0           NaN         NaN
min      4.000000  2022.0           NaN         NaN
25%     19.000000  2022.0           NaN         NaN
50%     31.000000  2022.0           NaN         NaN
75%     44.000000  2022.0           NaN         NaN
max     55.000000  2022.0           NaN         NaN

In [15]:
annual_hospitalizations.columns

Index(['StateFIPS', 'State', 'Year', 'Value', 'Data Comment', 'Unnamed: 5',
       'Age Group"Sex'],
      dtype='str')

In [16]:
#Renaming one of those columns for better readability
annual_hospitalizations.rename(columns={'Age Group"Sex': 'Age Group and Sex'}, inplace=True)

In [17]:
annual_hospitalizations.isna().sum()

StateFIPS              0
State                  0
Year                   0
Value                  0
Data Comment         270
Unnamed: 5           270
Age Group and Sex      0
dtype: int64

In [18]:
#Dropping the columns with NA values
annual_hospitalizations.drop(columns=['Data Comment', 'Unnamed: 5'], inplace=True)
print(annual_hospitalizations)

     StateFIPS      State  Year Value Age Group and Sex
0            4    Arizona  2022   279       0 TO 4"Male
1            4    Arizona  2022   154     0 TO 4"Female
2            4    Arizona  2022   382      5 TO 14"Male
3            4    Arizona  2022   289    5 TO 14"Female
4            4    Arizona  2022   139     15 TO 34"Male
..         ...        ...   ...   ...               ...
265         55  Wisconsin  2022   113   15 TO 34"Female
266         55  Wisconsin  2022    99     35 TO 64"Male
267         55  Wisconsin  2022   256   35 TO 64"Female
268         55  Wisconsin  2022    34        >= 65"Male
269         55  Wisconsin  2022   136      >= 65"Female

[270 rows x 5 columns]

In [19]:
annual_hospitalizations.duplicated().sum()

np.int64(0)

In [20]:
annual_hospitalizations.info()

<class 'pandas.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StateFIPS          270 non-null    int64
 1   State              270 non-null    str
 2   Year               270 non-null    int64
 3   Value              270 non-null    str
 4   Age Group and Sex  270 non-null    str
dtypes: int64(2), str(3)
memory usage: 10.7 KB

In [21]:
#I don't need the state fips code, so I'm going to drop that one too. The fips code is a unique identifier for each county in regards to accurate data collection, but it's not necessary for my analysis here
annual_hospitalizations.drop(columns=['StateFIPS'], inplace=True)
print(annual_hospitalizations)

         State  Year Value Age Group and Sex
0      Arizona  2022   279       0 TO 4"Male
1      Arizona  2022   154     0 TO 4"Female
2      Arizona  2022   382      5 TO 14"Male
3      Arizona  2022   289    5 TO 14"Female
4      Arizona  2022   139     15 TO 34"Male
..         ...   ...   ...               ...
265  Wisconsin  2022   113   15 TO 34"Female
266  Wisconsin  2022    99     35 TO 64"Male
267  Wisconsin  2022   256   35 TO 64"Female
268  Wisconsin  2022    34        >= 65"Male
269  Wisconsin  2022   136      >= 65"Female

[270 rows x 4 columns]

In [22]:
#Filtering the dataframe for Kentucky AQI data
kentucky_hospitalizations = annual_hospitalizations[annual_hospitalizations['State'] == 'Kentucky']
print(kentucky_hospitalizations)

       State  Year Value Age Group and Sex
80  Kentucky  2022   180       0 TO 4"Male
81  Kentucky  2022   111     0 TO 4"Female
82  Kentucky  2022   200      5 TO 14"Male
83  Kentucky  2022   134    5 TO 14"Female
84  Kentucky  2022    50     15 TO 34"Male
85  Kentucky  2022    91   15 TO 34"Female
86  Kentucky  2022    54     35 TO 64"Male
87  Kentucky  2022   167   35 TO 64"Female
88  Kentucky  2022    21        >= 65"Male
89  Kentucky  2022    89      >= 65"Female